from receipt import ReceiptText

if __name__ == '__main__':
    print(ReceiptText("ใบกำกับภาษีอย่างย่อ", 0, 'center'))
    print(ReceiptText("", 0, 'center'))
    print(ReceiptText("บริษัท เทคโนโลยีครัวไทย จำกัด (สำนักงานใหญ่)", 0, 'center'))
    print(ReceiptText("12/34 ม.5 ต.หกเจ็ด อ.แปดเก้า จ.สิบสิบ 11121", 0, 'center'))
    print(ReceiptText("โทร. 089-999-9999", 0, 'center'))
    print(ReceiptText("TaxID 0121231212100", 0, 'center'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("วันที่ 31 กุมภาพันธ์ 2565", 1) + ReceiptText("เลขที่ 6502310001", 1, 'right'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("รายการ", 12, 'left') + ReceiptText("หน่วยละ", 11, 'right') + ReceiptText("รวมเงิน", 1, 'right'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("2 มัสมันแกงแก้วตา", 1, 'left') + ReceiptText("20.00", 11, 'right') + ReceiptText("40.00", 1, 'right'))
    print(ReceiptText("2 หอมยี่หร่ารสร้อนแรง", 1, 'left') + ReceiptText("40.00", 11, 'right') + ReceiptText("80.00", 1, 'right'))
    print(ReceiptText("1 ชายใดได้กลืนแกง", 1, 'left') + ReceiptText("10.00", 11, 'right') + ReceiptText("10.00", 1, 'right'))
    print(ReceiptText("4 แรงอยากให้ใฝ่ฝันหา", 1, 'left') + ReceiptText("300.00", 11, 'right') + ReceiptText("1200.00", 1, 'right'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("รายการ: 4  จำนวนชิ้น: 9", 1, 'left'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("รวมเป็นเงิน", 1, 'left') + ReceiptText("1330.00", 1, 'right'))
    print(ReceiptText("ส่วนลด", 1, 'left') + ReceiptText("330.00", 1, 'right'))
    print(ReceiptText("รวมทั้งสิ้น", 1, 'left') + ReceiptText("1000.00", 1, 'right'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("รวมมูลค่าสินค้า", 1, 'left') + ReceiptText("934.58", 1, 'right'))
    print(ReceiptText("ภาษีมูลค่าเพิ่ม 7%", 1, 'left') + ReceiptText("65.42", 1, 'right'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("บัตรเครดิต/เดบิต", 1, 'left') + ReceiptText("1000.00", 1, 'right'))
    print(ReceiptText("ประเภท: VISA", 1, 'left'))
    print(ReceiptText("หมายเลข: 4123 **** **** 1234", 1, 'left'))
    print(ReceiptText("ชื่อหน้าบัตร: P. LUKKANATHITI", 1, 'left'))
    print(ReceiptText("วันหมดอายุ: 12/99", 1, 'left'))
    print(ReceiptText("ช่องทาง: CTLS", 1, 'left'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("บัตรสมาชิก: 0234 5678 1234 5678", 1, 'left'))
    print(ReceiptText("ชื่อสมาชิก: Phitchawat LUKKANATHITI", 1, 'left'))
    print(ReceiptText("คะแนนที่มี:", 1, 'left') + ReceiptText('1000 คะแนน', 23, 'right'))
    print(ReceiptText("คะแนนที่ได้:", 1, 'left') + ReceiptText('100 คะแนน', 23, 'right'))
    print(ReceiptText("คะแนนที่ใช้ไป:", 1, 'left') + ReceiptText('0 คะแนน', 23, 'right'))
    print(ReceiptText("คะแนนคงเหลือ:", 1, 'left') + ReceiptText('1100 คะแนน', 23, 'right'))
    print(ReceiptText("—" * ReceiptText.paper_width, 0, 'left'))
    print(ReceiptText("", 0, 'center'))
    print(ReceiptText("คะแนนที่ได้รับในวันนี้จะใช้แลกได้ในวันถัดไป", 0, 'center'))
    print(ReceiptText("ขอบคุณที่ใช้บริการ", 0, 'center'))
